# Generated by Django 5.2 on 2025-04-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('payment', 'Payment'), ('request', 'Request')], max_length=10)),
                ('is_request_accepted', models.BooleanField(default=False)),
            ],
        ),
    ]
